# Generated by Django 4.2.2 on 2023-07-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.CharField(default='Manager', max_length=100),
        ),
    ]
